### ISSUE TITLE
No resized version being generated

### ISSUE THREAD

**Issue by ghost** [franz-josef-kaiser/Dynamic-Image-Resize#13] opened 2016-02-09 16:33 UTC
I'm using this line in my PHP files, 

```
<?php echo dynamic_image_resize($gallerySet->before_img,120,90,'img-responsive');?>
```

But nothing is outputted. This doesn't generate a resized version to use as the src at all.

What I see as HTML output is

```
<img src="">
```

I need to be able to use this within my theme PHP files. What am I doing wrong, and how can I make this work?

**Comment by franz-josef-kaiser** [comment] 2016-02-09 23:39
Please do a `var_dump( $gallerySet );` and add it here. If you ain't got XDebug installed or available, please use

``` php
printf( '<pre>%s</pre>', var_export( $gallerySet, TRUE ) );
```

Thanks.

**Comment by ghost** [comment] 2016-02-09 23:49
It's a database row I created. I know it works.

On Tuesday, February 9, 2016, Franz Josef Kaiser notifications@github.com
wrote:

> Please do a var_dump( $gallerySet ); and add it here. If you ain't got
> XDebug installed or available, please use
> 
> printf( '<pre>%s</pre>', var_export( $gallerySet, TRUE ) );
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/franz-josef-kaiser/Dynamic-Image-Resize/issues/13#issuecomment-182134793
> .

## 

Regards,

_Lee_

**Comment by franz-josef-kaiser** [comment] 2016-02-09 23:55
@leecollings I didn't want to know if it works, I wanted to see the complete object… 

Closing as duplicate of #12

**Closed as completed by franz-josef-kaiser** 2016-02-09 23:55 UTC
